#!/bin/bash
set -e

ROOT=/var/opt/whmcs
PERSISTENT=/var/opt/persistent
test -d $ROOT || mkdir $ROOT
cd $ROOT

ARCHIVE=$(ls /whmcs*.zip)
if [ ! -d $ROOT/includes ];then
    unzip -o $ARCHIVE -d $ROOT
    if [[ ! -d $ROOT/install && -d $ROOT/whmcs ]];then
        mv $ROOT/whmcs/* $ROOT
        rm -rf $ROOT/whmcs
    fi
    cp /loghandler.php $ROOT/install
fi

for i in attachments downloads templates_c;do
    if [ ! -d $PERSISTENT/$i ];then
        cp -r $ROOT/$i $PERSISTENT
    fi
    rm -rf $ROOT/$i
done

if [ ! -d $PERSISTENT/crons ];then
    cp -r $ROOT/crons $PERSISTENT
    rm -f $PERSISTENT/crons/config.php.new
    echo "<?php" > $PERSISTENT/crons/config.php
    echo "\$whmcspath = '$ROOT';" >> $PERSISTENT/crons/config.php

fi
rm -rf $ROOT/crons

set +e
KDPLUGIN=$(ls $PERSISTENT/whmcs-kuberdock-plugin*.zip 2>/dev/null)
set -e
if [[ -n "$KDPLUGIN" && -e "$KDPLUGIN" ]];then
    unzip -o $KDPLUGIN -d $ROOT
    test $ROOT/deploy.php && rm -f $ROOT/deploy.php
fi

WHMCSCONF=$PERSISTENT/configuration.php
if [[ ! -e $WHMCSCONF ]];then
    echo "<?php" > $WHMCSCONF
    for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE;do
        if [[ ! -z ${!var} ]];then
            lcvar=$(echo "$var" | tr '[:upper:]' '[:lower:]')
            echo "\$$lcvar = '${!var}';" >> $WHMCSCONF
        fi
    done
    EHASH=$(openssl rand 64 | sha256sum | head -c 64)
    cat >> $WHMCSCONF <<EOF
\$cc_encryption_hash = '$EHASH';
\$attachments_dir = '$PERSISTENT/attachments';
\$downloads_dir = '$PERSISTENT/downloads';
\$templates_compiledir = '$PERSISTENT/templates_c';
\$crons_dir = '$PERSISTENT/crons';
\$mysql_charset = 'utf8';
EOF
    test -e $ROOT/configuration.php || ln -s $WHMCSCONF $ROOT
    chown www-data.www-data $WHMCSCONF
    COUNTER=1
    if [ -e /whmcs.sql ];then
        set +e
        while [[ $COUNTER -le 20 ]];do
            echo "Attempt $COUNTER to deploy from dump"
            mysql -u $DB_USERNAME -p$DB_PASSWORD -h $DB_HOST $DB_NAME < /whmcs.sql
            test $? -eq 0 && break
            COUNTER=$(( COUNTER+1 ))
            sleep 15
        done
        set -e
    elif [ -d $ROOT/install ];then
        while [[ $COUNTER -le 20 ]];do
            echo "Attempt $COUNTER to deploy"
            php install/bin/installer.php --install --non-interactive 2>&1 | tee $ROOT/install/deploy.log
            grep -qi "^\(username\|password\)" $ROOT/install/deploy.log && break
            COUNTER=$(( COUNTER+1 ))
            sleep 15
        done
    fi
fi
test -e $ROOT/configuration.php || ln -s $WHMCSCONF $ROOT

php /preset.php

for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE TEMPLATES_COMPILEDIR PASSWORD SMTP_USERNAME SMTP_PASSWORD SMTP_HOST;do
    unset $var
done

set +e
rm -rf $ROOT/install
chown -R www-data.www-data $ROOT/*
chown -R www-data.www-data $PERSISTENT/*
set -e

grep -q "DB_PASSWORD LICENSE" /root/.bashrc > /dev/null 2>&1 \
    || echo "for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE PASSWORD SMTP_USERNAME SMTP_PASSWORD SMTP_HOST;do unset \$var;done" >> /root/.bashrc

crontab -l | grep -q "cron.php|dbdump.sh" || (echo "0 0  *  *  * php -q $PERSISTENT/crons/cron.php"; echo "30 23  *  *  * /dbdump.sh") | crontab -

exec /usr/sbin/php5-fpm