#!/bin/bash
set -e

ROOT=/var/opt/whmcs
PERSISTENT=/var/opt/persistent
test -d $ROOT || mkdir $ROOT
cd $ROOT

ARCHIVE=$(ls /whmcs*.zip)
if [ ! -d $ROOT/includes ];then
    unzip -o $ARCHIVE -d $ROOT
    if [[ ! -d $ROOT/install && -d $ROOT/whmcs ]];then
        mv $ROOT/whmcs/* $ROOT
        rm -rf $ROOT/whmcs
    fi
    cp /loghandler.php $ROOT/install
fi

for i in attachments downloads templates_c;do
    if [ ! -d $PERSISTENT/$i ];then
        cp -r $ROOT/$i $PERSISTENT
    fi
    rm -rf $ROOT/$i
done

if [ ! -d $PERSISTENT/crons ];then
    cp -r $ROOT/crons $PERSISTENT
    rm -f $PERSISTENT/crons/config.php.new
    echo "<?php" > $PERSISTENT/crons/config.php
    echo "\$whmcspath = '$ROOT';" >> $PERSISTENT/crons/config.php
    
fi
rm -rf $ROOT/crons

mkdir -p $PERSISTENT/admin/lang/overrides $PERSISTENT/lang/overrides
rm -rf $ROOT/admin/lang/overrides $ROOT/lang/overrides
ln -s $PERSISTENT/admin/lang/overrides $ROOT/admin/lang
ln -s $PERSISTENT/lang/overrides $ROOT/lang
chown -R www-data.www-data $PERSISTENT/admin/lang/overrides $PERSISTENT/lang/overrides

mkdir -p $PERSISTENT/resources/{domains,country}
touch $PERSISTENT/resources/domains/whois.json
touch $PERSISTENT/resources/domains/additionalfields.php
touch $PERSISTENT/resources/country/countries.json
rm -f $ROOT/resources/domains/whois.json $ROOT/resources/domains/additionalfields.php $ROOT/resources/country/countries.json
ln -s $PERSISTENT/resources/domains/whois.json $ROOT/resources/domains
ln -s $PERSISTENT/resources/domains/additionalfields.php $ROOT/resources/domains
ln -s $PERSISTENT/resources/country/countries.json $ROOT/resources/country
chown -R www-data.www-data $PERSISTENT/resources

set +e
KDPLUGIN=$(ls $PERSISTENT/whmcs-kuberdock-plugin*.zip 2>/dev/null)
set -e
if [[ -n "$KDPLUGIN" && -e "$KDPLUGIN" ]];then
    unzip -o $KDPLUGIN -d $ROOT
    test $ROOT/deploy.php && rm -f $ROOT/deploy.php
fi

# We need a license to be always present
if [ -z "$LICENSE" ];then
    LICENSE=Hosted-123456789a123456789b
fi

WHMCSCONF=$PERSISTENT/configuration.php
if [[ ! -e $WHMCSCONF ]];then
    echo "<?php" > $WHMCSCONF
    for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE;do
        if [[ ! -z ${!var} ]];then
            lcvar=$(echo "$var" | tr '[:upper:]' '[:lower:]')
            echo "\$$lcvar = '${!var}';" >> $WHMCSCONF
        fi
    done
    EHASH=$(openssl rand 64 | sha256sum | head -c 64)
    cat >> $WHMCSCONF <<EOF
\$cc_encryption_hash = '$EHASH';
\$attachments_dir = '$PERSISTENT/attachments';
\$downloads_dir = '$PERSISTENT/downloads';
\$templates_compiledir = '$PERSISTENT/templates_c';
\$crons_dir = '$PERSISTENT/crons';
\$mysql_charset = 'utf8';
EOF
    test -e $ROOT/configuration.php || ln -s $WHMCSCONF $ROOT
    chown www-data.www-data $WHMCSCONF
    COUNTER=1
    set +e
    while [[ $COUNTER -le 20 ]];do
        echo "Attempt $COUNTER to deploy from dump"
        mysql -u $DB_USERNAME -p$DB_PASSWORD -h $DB_HOST $DB_NAME < /whmcs.sql
        test $? -eq 0 && break
        COUNTER=$(( COUNTER+1 ))
        sleep 15
    done
    set -e
else
    VERSIONS=/updates/versions.txt
    if [ -e $VERSIONS ];then
        CURRENT=$(tail -n 1 $VERSIONS)
        COUNTER=1
        set +e
        while [[ $COUNTER -le 20 ]];do
            echo "Attempt $COUNTER to get current version..."
            LAST=$(mysql -u $DB_USERNAME -p$DB_PASSWORD -h $DB_HOST $DB_NAME --skip-column-names -e "SELECT value FROM tblconfiguration WHERE setting='Version'")
            EXIT_CODE=$?
            test $EXIT_CODE -eq 0 && break
            COUNTER=$(( COUNTER+1 ))
            sleep 15
        done
        set -e
        if [[ "$EXIT_CODE" -eq 0 && "$LAST" != "$CURRENT" ]];then
            POS=$(grep -n $LAST $VERSIONS|cut -f1 -d:)
            if [ -z "$POS" ]; then
                while IFS= read -r LINE;do
                    DUMPS+=($LINE)
                done < $VERSIONS
                [[ $LINE ]] && DUMPS+=("$LINE")
            else
                POS=$(( POS+1 ))
                while IFS= read -r LINE;do
                    DUMPS+=($LINE)
                done < <(tail --lines=+$POS $VERSIONS)
                [[ $LINE ]] && DUMPS+=("$LINE")
            fi
            for i in ${DUMPS[@]};do
                echo "Applying $i..."
                mysql -u $DB_USERNAME -p$DB_PASSWORD -h $DB_HOST $DB_NAME < /updates/$i.sql
            done
        fi
    fi
fi
test -e $ROOT/configuration.php || ln -s $WHMCSCONF $ROOT

php /preset.php

for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE TEMPLATES_COMPILEDIR PASSWORD SMTP_USERNAME SMTP_PASSWORD SMTP_HOST;do
    unset $var
done

set +e
rm -rf $ROOT/install
chown -R www-data.www-data $ROOT/*
chown -R www-data.www-data $PERSISTENT/*
chown root.root $WHMCSCONF
set -e

grep -q "DB_PASSWORD LICENSE" /root/.bashrc > /dev/null 2>&1 \
    || echo "for var in DB_USERNAME DB_HOST DB_NAME DB_PASSWORD LICENSE PASSWORD SMTP_USERNAME SMTP_PASSWORD SMTP_HOST;do unset \$var;done" >> /root/.bashrc

HOUR=$(($RANDOM%24))
MIN=$(($RANDOM%60))
crontab -l | grep -q "cron.php|dbdump.sh" || (echo "*/5 *  *  *  * php -q $PERSISTENT/crons/cron.php"; echo "$MIN $HOUR  *  *  * /dbdump.sh"; echo "*/5 * * * * php -q /var/opt/persistent/crons/pop.php";) | crontab -

exec /usr/sbin/php5-fpm